updated dockerfile

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -3,13 +3,15 @@ FROM node:18-alpine
 WORKDIR /app
 
 COPY package*.json ./
-RUN npm install
 
+# Install deps
+RUN npm install
 
 COPY . .
 
-RUN npx prisma generate
+# Prisma generate should NOT fail build
+RUN npx prisma generate || true
 
 EXPOSE 5000
 
-CMD ["npm", "run", "dev"]
+CMD ["npm", "start"]
